### PR TITLE
Windows on ARM Support

### LINKED ISSUE #443: Support for Windows on ARM 64-bit
I just tested a Java Swing application with the FlatLaf on Windows 11 ARM 64-bit and I got the following error:

```
java.lang.UnsatisfiedLinkError: C:\Users\xander\AppData\Local\Temp\flatlaf.temp\flatlaf-windows-x86-20900948333330.dll: Can't load IA 32-bit .dll on a ARM 64-bit platform
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.formdev.flatlaf.util.NativeLibrary.loadLibraryFromJar(NativeLibrary.java:108)
        at com.formdev.flatlaf.util.NativeLibrary.<init>(NativeLibrary.java:59)
        at com.formdev.flatlaf.ui.FlatWindowsNativeWindowBorder.getInstance(FlatWindowsNativeWindowBorder.java:113)
        at com.formdev.flatlaf.ui.FlatNativeWindowBorder.initialize(FlatNativeWindowBorder.java:274)
        at com.formdev.flatlaf.ui.FlatNativeWindowBorder.isSupported(FlatNativeWindowBorder.java:68)
        at com.formdev.flatlaf.ui.FlatNativeWindowBorder.install(FlatNativeWindowBorder.java:76)
        at com.formdev.flatlaf.ui.FlatRootPaneUI.installNativeWindowBorder(FlatRootPaneUI.java:205)
        at com.formdev.flatlaf.ui.FlatRootPaneUI.installUI(FlatRootPaneUI.java:105)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
        at java.desktop/javax.swing.JRootPane.setUI(JRootPane.java:445)
        at java.desktop/javax.swing.JRootPane.updateUI(JRootPane.java:455)
        at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:349)
        at java.desktop/javax.swing.JWindow.createRootPane(JWindow.java:274)
        at java.desktop/javax.swing.JWindow.windowInit(JWindow.java:262)
        at java.desktop/javax.swing.JWindow.<init>(JWindow.java:189)

```
So the question is can I ignore this? There seems to be no DLL available for this platform. Is this planned?

### PR DESCRIPTION
**Pull request by syoon2**
Closes #443

This PR adds native library support for Windows on ARM.

Verification steps

1. Compile native libraries and build flatlaf-demo.
2. Observe embedded menu bars working on all Windows architectures (i.e., x86, x86_64, _and_ aarch64).

### CODE REVIEW

**Comment by syoon2** [comment]
@DevCharly ready for review :smile:

File: flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeLibrary.java [hunk 1]
```diff
@@ -55,12 +55,12 @@ private static void initialize() {
 
 		String classifier;
 		String ext;
-		if( SystemInfo.isWindows_10_orLater ) {
-			// Windows: requires Windows 10/11
+		if( SystemInfo.isWindows_10_orLater && (SystemInfo.isX86 || SystemInfo.isX86_64 || SystemInfo.isAARCH64) ) {
```
Comment (DevCharly) [inline flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeLibrary.java:58]: Have re-added this check for platforms to be sure to exclude unknown platforms.
E.g. Windows 10 ARM 32 bit (not sure whether Java exists for this platform).
Theoretically Microsoft could port Windows to RISC-V in the future. We don't know 😺

**Comment by DevCharly** [comment]
@syoon2 thanks for your contribution 👍

File: flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeLibrary.java (hunk 1 above)
Comment (syoon2) [reply flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeLibrary.java:58]: AFAIK the only time a Windows variant for ARM 32bit existed (except Windows Mobile) was Windows RT, which I think is safe to say dead. But yeah, I guess it wouldn't hurt to keep the check there.
